title = 'Desa Pengadang'

contentDir = 'content/en'
languageName = 'English'
languageCode = 'en-US'

copyright = 'All rights reserved'

weight = 1

[params]
    description = 'Website Profil Desa Pengadang, Kecamatan Sekayam, Kabupaten Sanggau, Provinsi Kalimantan Barat'